name: Tests

on:
  push:
    branches:
      - main
    pull_request:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [15.x, 16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.1.1
      - name: Set up NodeJS ${{matrix.node_version}}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{matrix.node_version}}
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test-ci
